name: "Trivy Image Scan"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  trivy-scan:
    name: "Scan Docker Image with Trivy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t devops-ai-monitoring-agent:latest ./ai_service

      - name: Install Trivy
        run: |
          wget -O trivy.deb https://github.com/aquasecurity/trivy/releases/download/v0.75.0/trivy_0.75.0_Linux-64bit.deb
          echo "b6d7b944b6cbf4e7de5b4bc6c3635900c50fed53b64b77b99a5fbc3136cd1d5d  trivy.deb" | sha256sum --check
          sudo dpkg -i trivy.deb

      - name: Run Trivy scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL devops-ai-monitoring-agent:latest
